### PR TITLE
Fix CIS control ids

### PR DESCRIPTION
**Pull request by mfortin**
**Overall Review of Changes:**
CIS control ids mismatch

**Issue Fixes:**
Update ID, removed one and fixed order of others

**Enhancements:**
none

**How has this been tested?:**
Ansible playbook from a local workstation to an EC2 instance in AWS

### CODE REVIEW

**Comment by frederickw082922** [comment]
Thank you for the PR @mfortin ! The playbook failed during the Pipeline run!

**Comment by mfortin** [comment]
@frederickw082922 I fixed the rule condition, there was a typo there too.

**Comment by mfortin** [comment]
There are still 2 updates that did not get ported in #100. One is minor, the other one prevents this role from executing on Amazon EC2 instances due to a race condition related to the ordering of controls in section 01.

**Review by frederickw082922 — APPROVED** [review]
Nice work @mfortin ! Thank you!

**Pull request merged**
